name: BungeeWarped
version: 0.8
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: MCShovel
main: com.steamcraftmc.BungeeWarped.BungeeWarpedBukkitPlugin
dev-url: https://github.com/MCShovel/BungeeWarped
softdepend: [WorldEdit]

commands:
    portal:
        aliases: [bw]
        description: 'Administration help and commands.'
        usage: 'Use /<command> for help using this command.'
        permission: bungeewarped.portal
        permission-message: '§4You do not have permission to perform this action.'
    warp:
        aliases: [warps]
        description: 'Teleport to a warp by name, or lists the warps.'
        usage: 'Usage: /<command> [name]'
        permission: bungeewarped.warp
        permission-message: '§4You do not have permission to perform this action.'
    setwarp:
        aliases: [createwarp]
        description: 'Creates a named warp at your current location.'
        usage: 'Usage: /<command> name'
        permission: bungeewarped.setwarp
        permission-message: '§4You do not have permission to perform this action.'
    delwarp:
        aliases: [remwarp, rmwarp]
        description: 'Removes a named warp if it exists.'
        usage: 'Usage: /<command> name'
        permission: bungeewarped.setwarp
        permission-message: '§4You do not have permission to perform this action.'
    home:
        aliases: [homes]
        description: 'Teleport to your home.'
        usage: 'Usage: /<command> [name]'
        permission: bungeewarped.home
        permission-message: '§4You do not have permission to perform this action.'
    sethome:
        aliases: [createhome]
        description: 'Set a home to your current position.'
        usage: 'Usage: /<command> [name]'
        permission: bungeewarped.home
        permission-message: '§4You do not have permission to perform this action.'
    delhome:
        aliases: [remhome, rmhome]
        description: 'Remove your home by name.'
        usage: 'Usage: /<command> [name]'
        permission: bungeewarped.home
        permission-message: '§4You do not have permission to perform this action.'
    tpo:
        description: 'Force teleport a player.'
        usage: 'Usage: /<command> player [player]'
        permission: bungeewarped.tpo
        permission-message: '§4You do not have permission to perform this action.'
    tppos:
        description: 'Force teleport to a specific location.'
        usage: 'Usage: /<command> x y z [yaw] [pitch] [world] [server]'
        permission: bungeewarped.tppos
        permission-message: '§4You do not have permission to perform this action.'
    tpa:
        aliases: [call, tpask]
        description: 'Request to teleport to another player.'
        usage: 'Usage: /<command> player'
        permission: bungeewarped.tpa
        permission-message: '§4You do not have permission to perform this action.'
    tpahere:
        description: 'Request another player to teleport to you.'
        usage: 'Usage: /<command> player'
        permission: bungeewarped.tpahere
        permission-message: '§4You do not have permission to perform this action.'
    tpaccept:
        aliases: [tpyes]
        description: 'Accept the pending teleport request.'
        usage: 'Usage: /<command>'
        permission: bungeewarped.tpaccept
        permission-message: '§4You do not have permission to perform this action.'
    tpdeny:
        aliases: [tpno]
        description: 'Deny the pending teleport request.'
        usage: 'Usage: /<command>'
        permission: bungeewarped.tpaccept
        permission-message: '§4You do not have permission to perform this action.'
    tptoggle:
        description: 'Stop recieving teleport requests.'
        usage: 'Usage: /<command>'
        permission: bungeewarped.tpaccept
        permission-message: '§4You do not have permission to perform this action.'

permissions:
    bungeewarped.*:
        description: Gives access to all commands
        default: op

    bungeewarped.bypass.*:
        description: Allows operators to bypass all warmups/cooldowns
        default: op
    bungeewarped.bypass.home:
        description: Allows users to bypass warmup/cooldown of /home
    bungeewarped.bypass.portal:
        description: Allows users to bypass warmup/cooldown of portal use
    bungeewarped.bypass.warp:
        description: Allows users to bypass warmup/cooldown of /warp use
    bungeewarped.bypass.tpa:
        description: Allows users to bypass warmup/cooldown of /tpa use
    bungeewarped.bypass.combat:
        description: Allows users to bypass the combat cooldown

#Portal Related perms
    bungeewarped.portal:
        description: 'Allowes to access create/delete portals.'
        default: op

    bungeewarped.vanillaportals:
        description: 'Allows users to teleport with vanilla portals'
        default: true

#Warp location perms
    bungeewarped.warp:
        description: 'Access to the /warp command.'
        default: false

    bungeewarped.setwarp:
        description: 'Access to create/move warps.'
        default: false

    bungeewarped.location.*:
        description: 'Access to all warp/portal locations.'
        default: true

#Teleport perms
    bungeewarped.tpaccept:
        description: 'Access to accept/deny/toggle requests.'
        default: true

    bungeewarped.tpa:
        description: 'Access to use /tpa command.'
        default: true

    bungeewarped.tpahere:
        description: 'Access to use /tpahere command.'
        default: true

    bungeewarped.tpo:
        description: 'Access to /tpo to force teleport players.'
        default: op

    bungeewarped.tppos:
        description: 'Access to /tppos to teleport to a locatoin.'
        default: op

#Home user permissions
    bungeewarped.home:
        description: 'Access to use home commands.'
        default: true
    bungeewarped.home.others:
        description: 'Access to list/tp to other player homes.'
        default: true

    bungeewarped.home.multi.1:
        description: 'Assumed if you have access to bungeewarped.home.create.'
        default: false
    bungeewarped.home.multi.2:
        description: 'Allows a user to have 2 named homes.'
        default: false
        children:
            bungeewarped.home.multi.1: true
    bungeewarped.home.multi.3:
        description: 'Allows a user to have 3 named homes.'
        default: false
        children:
            bungeewarped.home.multi.2: true
    bungeewarped.home.multi.4:
        description: 'Allows a user to have 4 named homes.'
        default: false
        children:
            bungeewarped.home.multi.3: true
    bungeewarped.home.multi.5:
        description: 'Allows a user to have 5 named homes.'
        default: false
        children:
            bungeewarped.home.multi.4: true
    bungeewarped.home.unlimited:
        description: 'Allows a user to have unlimited named homes.'
        default: false
