name: BungeePortals
version: 0.8
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: MCShovel, YoFuzzy3
main: com.steamcraftmc.BungeeWarped.BungeeWarpedBukkitPlugin
dev-url: https://github.com/MCShovel/BungeeWarped
softdepend: [WorldEdit]

commands:
    bw:
        description: Administration help and commands.
permissions:
    bungeewarped.admin:
        description: Allowed to access the command /bw
        default: op
    bungeewarped.portal.*:
        description: Access to all portals.
        default: true
